<?php

namespace Apitic\AnimalsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AnimalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalsRepository extends EntityRepository
{
	public function getAnimals($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('a')
        ->join('a.type', 't')
        ->addSelect('t')
        ->getQuery()
        ;

        $query
        ->setFirstResult(($page-1) * $nbPerPage)
        ->setMaxResults($nbPerPage)
        ;

        return new Paginator($query, true);
    }
}
