<?php

namespace Apitic\AnimalsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypesRepository extends EntityRepository
{
}
